name: Deploy to Server

on:
  push:
    branches:
      - master # 或者您想要觸發部署的其他分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync files to temporary directory
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan mario.bency.org >> ~/.ssh/known_hosts
          rsync -avz --delete --no-times --no-perms --exclude='.git' --exclude='.env' -e "ssh -o StrictHostKeyChecking=no" ./ bency@mario.bency.org:/tmp/traffic.keeping.work

      - name: Move files to target directory and set permissions
        run: |
          ssh -o StrictHostKeyChecking=no bency@mario.bency.org << 'EOF'
          sudo rsync -avz --delete --no-times --no-perms  --exclude='.env' /tmp/traffic.keeping.work/ /var/www/traffic.keeping.work
          sudo chown -R www-data:www-data /var/www/traffic.keeping.work
          EOF

      - name: Install dependencies and build assets
        run: |
          ssh -o StrictHostKeyChecking=no bency@mario.bency.org << 'EOF'
          cd /var/www/traffic.keeping.work
          composer install --no-dev
          npm install
          npm run build
          EOF
