name: Deploy to Server

on:
  push:
    branches:
      - master # 或者您想要觸發部署的其他分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync files
        run: |
          rsync -avz --delete --no-times --exclude='.git' -e "ssh -o StrictHostKeyChecking=no" ./ bency@mario.bency.org:/var/www/traffic.keeping.work

      - name: Install dependencies and build assets
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no bency@mario.bency.org << 'EOF'
          cd /var/www/traffic.keeping.work
          composer install --no-dev
          npm install
          npm run production
          php artisan migrate --force
          EOF
